name: Codestyle Checker ðŸ˜Ž

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources ðŸ“„
        uses: actions/checkout@v6

      - name: Set up editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      - name: Run editorconfig-checker
        run: editorconfig-checker
